name: Docker for image capable of running R with all required packages

on:
  push:
    branches: [ main ]

env:
  # Use GitHub Packages as registry
  REGISTRY: ghcr.io
  # Image name will be the same as the repository ( <account>/<repo>)
  IMAGE_NAME: ${{ github.repository }}


jobs:
  # Push image to GitHub Packages.
  # See https://docs.docker.com/build/ci/github-actions/
  # and https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out docker files
        uses: actions/checkout@v4
        with:
          sparse-checkout:
            - docker
            - runner

      - name: Run file diff checking image
        id: changed-docker-files
        uses: tj-actions/changed-files@v45
        with:
          files: docker/**

      - name: Log in to registry
        uses: docker/login-action@v3
        if: steps.changed-docker-files.outputs.any_changed == 'true'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.changed-docker-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        if: steps.changed-docker-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:docker"
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # Rebuild GitHub runner when image changes
      - name: Build runner
        uses: ./.github/workflows/deploy-runner-image.yml
