name: Test integrity of R code

on:
  workflow_dispatch:
  push:
    paths:
      - '**.R'
      - '**.Rda'

jobs:
  test-code:
    runs-on: election-inferences
    steps:
      - name: Check out all files except model output, inferences.Rda
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Lint
        run: lintr::lint_dir()
        shell: Rscript {0}

      - name: Check if analyze_results.R file changed
        id: changed-analysis
        uses: tj-actions/changed-files@v45
        with:
          files: analyze_results.R.not_now

      - name: Check out model output, inferences.Rda
        if: steps.changed-analysis.outputs.any_changed == 'true'
        uses: actions/checkout@v4
        with:
          lfs: true
          sparse-checkout: |
            inferences.Rda

      - name: Test inference code
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: Rscript test.R

      - name: Test analysis code
        if: steps.changed-analysis.outputs.any_changed == 'true'
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: Rscript analyze_results.R
