name: Test integrity of R code

on:
  push:

jobs:
  test-code:
    runs-on: election-inferences
    steps:
      - name: Check out all files except model output, inferences.Rda
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Check if any *.R files changed
        id: changed-r-files
        uses: tj-actions/changed-files@v45
        with:
          files: '*.R'

      - name: Check if analyze_results.R  file changed
        id: changed-analysis
        uses: tj-actions/changed-files@v45
        with:
          files: analyze_results.R

      - name: Check out model output, inferences.Rda
        if: steps.changed-analysis.outputs.any_changed == 'true'
        uses: actions/checkout@v4
        with:
          lfs: true
          sparse-checkout: |
            inferences.Rda

      - name: Test inference code
        if: steps.changed-r-files.outputs.any_changed == 'true'
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: Rscript test.R

      - name: Test analysis code
        if: steps.changed-analysis.outputs.any_changed == 'true'
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: Rscript analyze_results.R
